import pandas as pd
import matplotlib.pylab as plt

# result(variable_coupling_density) = pd.read_csv("result(variable_coupling_density).csv")
#
# fig1 = plt.figure(1)
# ax = fig1.add_subplot(211)
# ax.plot(result(variable_coupling_density)['ny'], result(variable_coupling_density)['total time[MDF]'], label='MDF')
# ax.plot(result(variable_coupling_density)['ny'], result(variable_coupling_density)['total time[IDF]'], label='IDF_TOL = 1e-6')
# ax.plot(result(variable_coupling_density)['ny'], result(variable_coupling_density)['total time[IDF_tol]'], label='IDF_TOL = 1e-3')
# plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'))
# plt.xlabel('ny', fontsize=12)
# plt.title('nx = 7(no PreMDA)')
# plt.ylabel('wall time')
#
# result_preMDA = pd.read_csv("result_preMDA.csv")
# ax = fig1.add_subplot(212)
# ax.plot(result_preMDA['ny'], result_preMDA['total time[MDF]'], label='MDF')
# ax.plot(result_preMDA['ny'], result_preMDA['total time[IDF]'], label='IDF_TOL = 1e-6')
# ax.plot(result_preMDA['ny'], result_preMDA['total time[IDF_tol]'], label='IDF_TOL = 1e-3')
# plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'))
# plt.xlabel('ny', fontsize=12)
# plt.title('nx = 7(PreMDA)')
# plt.ylabel('wall time')
# plt.tight_layout()
#
#
# result_coupling_density = pd.read_csv("result_coupling_density.csv")
# result_coupling_density2 = pd.read_csv("result_coupling_density2.csv")
# fig2 = plt.figure(2)
# ny_range = ['ny = 2', 'ny = 7', 'ny=8', 'ny = 9']
# for i in range(4):
#     ax = fig2.add_subplot(3, 2, i + 1)
#     ax.plot(result_coupling_density['d'][6 * i:6 * i + 6], result_coupling_density['total time[MDF]'][6 * i: 6 * i + 6],
#             label='MDF')
#     ax.plot(result_coupling_density['d'][6 * i:6 * i + 6], result_coupling_density['total time[IDF]'][6 * i: 6 * i + 6],
#             label='IDF')
#     ax.plot(result_coupling_density['d'][6 * i:6 * i + 6], result_coupling_density['total time[IDF_tol]'][6 * i:6 * i + 6],
#             label='IDF_tol')
#     plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
#     plt.xlabel('coupling density', fontsize=12)
#     plt.title(ny_range[i])
#     plt.ylabel('wall time')
#     plt.tight_layout()
# ax = fig2.add_subplot(3, 2, 5)
# ax.plot(result_coupling_density2['d'][0:6], result_coupling_density2['total time[MDF]'][0:6],
#         label='MDF')
# ax.plot(result_coupling_density2['d'][0:6], result_coupling_density2['total time[IDF]'][0:6],
#         label='IDF')
# ax.plot(result_coupling_density2['d'][0:6], result_coupling_density2['total time[IDF_tol]'][0:6],
#         label='IDF_tol')
# plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
# ax = fig2.add_subplot(3, 2, 6)
# ax.plot(result_coupling_density2['d'][6:11], result_coupling_density2['total time[MDF]'][6:11],
#         label='MDF')
# ax.plot(result_coupling_density2['d'][6:11], result_coupling_density2['total time[IDF]'][6:11],
#         label='IDF')
# ax.plot(result_coupling_density2['d'][6:11], result_coupling_density2['total time[IDF_tol]'][6:11],
#         label='IDF_tol')
# plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)


fig3 = plt.figure(3)
ax = fig3.add_subplot(321)
result = pd.read_csv("result_coupling_density(nx = 6).csv")
ax.plot(result['ny'][0:8], result['total time[MDF]'][0:8], label='MDF')
ax.plot(result['ny'][0:8], result['total time[IDF]'][0:8], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][0:8], result['total time[IDF_tol]'][0:8], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 6, density = .3', fontsize=10)
plt.ylabel('wall time')

ax = fig3.add_subplot(322)
result = pd.read_csv("result_coupling_density(nx = 6).csv")
ax.plot(result['ny'][8:16], result['total time[MDF]'][8:16], label='MDF')
ax.plot(result['ny'][8:16], result['total time[IDF]'][8:16], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][8:16], result['total time[IDF_tol]'][8:16], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 6, density = .4', fontsize=10)
plt.ylabel('wall time')

ax = fig3.add_subplot(323)
result = pd.read_csv("result_coupling_density(nx = 6).csv")
ax.plot(result['ny'][16:24], result['total time[MDF]'][16:24], label='MDF')
ax.plot(result['ny'][16:24], result['total time[IDF]'][16:24], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][16:24], result['total time[IDF_tol]'][16:24], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 6, density = .5', fontsize=10)
plt.ylabel('wall time')

ax = fig3.add_subplot(324)
result = pd.read_csv("result_coupling_density(nx = 6).csv")
ax.plot(result['ny'][24:32], result['total time[MDF]'][24:32], label='MDF')
ax.plot(result['ny'][24:32], result['total time[IDF]'][24:32], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][24:32], result['total time[IDF_tol]'][24:32], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 6, density = .6', fontsize=10)
plt.ylabel('wall time')

ax = fig3.add_subplot(325)
result = pd.read_csv("result_coupling_density(nx = 6).csv")
ax.plot(result['ny'][32:40], result['total time[MDF]'][32:40], label='MDF')
ax.plot(result['ny'][32:40], result['total time[IDF]'][32:40], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][32:40], result['total time[IDF_tol]'][32:40], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 6, density = .7', fontsize=10)
plt.ylabel('wall time')
plt.tight_layout()
#

fig4 = plt.figure(4)
ax = fig4.add_subplot(321)
result = pd.read_csv("result_coupling_density(nx = 7).csv")
ax.plot(result['ny'][0:8], result['total time[MDF]'][0:8], label='MDF')
ax.plot(result['ny'][0:8], result['total time[IDF]'][0:8], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][0:8], result['total time[IDF_tol]'][0:8], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 7, density = .3', fontsize=10)
plt.ylabel('wall time')

ax = fig4.add_subplot(322)
result = pd.read_csv("result_coupling_density(nx = 7).csv")
ax.plot(result['ny'][8:16], result['total time[MDF]'][8:16], label='MDF')
ax.plot(result['ny'][8:16], result['total time[IDF]'][8:16], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][8:16], result['total time[IDF_tol]'][8:16], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 7, , density = .4', fontsize=10)
plt.ylabel('wall time')

ax = fig4.add_subplot(323)
result = pd.read_csv("result_coupling_density(nx = 7).csv")
ax.plot(result['ny'][16:24], result['total time[MDF]'][16:24], label='MDF')
ax.plot(result['ny'][16:24], result['total time[IDF]'][16:24], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][16:24], result['total time[IDF_tol]'][16:24], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 7, density = .5', fontsize=10)
plt.ylabel('wall time')

ax = fig4.add_subplot(324)
result = pd.read_csv("result_coupling_density(nx = 7).csv")
ax.plot(result['ny'][24:32], result['total time[MDF]'][24:32], label='MDF')
ax.plot(result['ny'][24:32], result['total time[IDF]'][24:32], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][24:32], result['total time[IDF_tol]'][24:32], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 7, density = .6', fontsize=10)
plt.ylabel('wall time')

ax = fig4.add_subplot(325)
result = pd.read_csv("result_coupling_density(nx = 7).csv")
ax.plot(result['ny'][32:40], result['total time[MDF]'][32:40], label='MDF')
ax.plot(result['ny'][32:40], result['total time[IDF]'][32:40], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][32:40], result['total time[IDF_tol]'][32:40], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 7, density = .7', fontsize=10)
plt.ylabel('wall time')

ax = fig4.add_subplot(326)
result = pd.read_csv("result_coupling_density(nx = 7).csv")
ax.plot(result['ny'][40:48], result['total time[MDF]'][40:48], label='MDF')
ax.plot(result['ny'][40:48], result['total time[IDF]'][40:48], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][40:48], result['total time[IDF_tol]'][40:48], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 7, density = .8', fontsize=10)
plt.ylabel('wall time')
plt.tight_layout()


fig5 = plt.figure(5)
ax = fig5.add_subplot(321)
result = pd.read_csv("result_coupling_density(nx = 5).csv")
ax.plot(result['ny'][0:5], result['total time[MDF]'][0:5], label='MDF')
ax.plot(result['ny'][0:5], result['total time[IDF]'][0:5], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][0:5], result['total time[IDF_tol]'][0:5], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 5, density = .3', fontsize=10)
plt.ylabel('wall time')

ax = fig5.add_subplot(322)
ax.plot(result['ny'][5:10], result['total time[MDF]'][5:10], label='MDF')
ax.plot(result['ny'][5:10], result['total time[IDF]'][5:10], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][5:10], result['total time[IDF_tol]'][5:10], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 5, , density = .4', fontsize=10)
plt.ylabel('wall time')
#
ax = fig5.add_subplot(323)
ax.plot(result['ny'][10:15], result['total time[MDF]'][10:15], label='MDF')
ax.plot(result['ny'][10:15], result['total time[IDF]'][10:15], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][10:15], result['total time[IDF_tol]'][10:15], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 5, density = .5', fontsize=10)
plt.ylabel('wall time')
#
ax = fig5.add_subplot(324)
ax.plot(result['ny'][15:20], result['total time[MDF]'][15:20], label='MDF')
ax.plot(result['ny'][15:20], result['total time[IDF]'][15:20], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][15:20], result['total time[IDF_tol]'][15:20], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 5, density = .6', fontsize=10)
plt.ylabel('wall time')
#
ax = fig5.add_subplot(325)
ax.plot(result['ny'][20:25], result['total time[MDF]'][20:25], label='MDF')
ax.plot(result['ny'][20:25], result['total time[IDF]'][20:25], label='IDF_TOL = 1e-6')
ax.plot(result['ny'][20:25], result['total time[IDF_tol]'][20:25], label='IDF_TOL = 1e-3')
plt.gca().legend(('MDF', 'IDF_TOL = 1e-6', 'IDF_TOL = 1e-3'), fontsize=5)
plt.xlabel('ny', fontsize=10)
plt.title('nx = 5, density = .7', fontsize=10)
plt.ylabel('wall time')
plt.tight_layout()
plt.show()
